README.md added.  Major refactor of the project.

diff --git a/v4l2loopbackInit b/v4l2loopbackInit
--- a/v4l2loopbackInit
+++ b/v4l2loopbackInit
@@ -10,38 +10,44 @@ type -p pd || pd () {
     ${DEBUG:-false} && echo -ne "[$progn-${BASH_LINENO[0]}] $*\n" >&2 ; true
 }
 
+runfile=/tmp/v4l2loopback.run
 
-# modCheck checks if the v4l2loopback module is loaded and sets VID1, VID2, and modOptions if not.
+# modCheck checks if the v4l2loopback module is loaded. Sets VID1, VID2, and modOptions.
 modCheck () {
     if lsmod | grep -q v4l2loopback ; then
-        pd "v4l2loopback module is already loaded."
+        echo "v4l2loopback module is already loaded." >&2
         pushd /sys/devices/virtual/video4linux/ &> /dev/null
         vids=( video* )
-        VID1=${vids[0]#video}
-        VID2=${vids[1]#video}
-        modOptions=(video_nr=$VID1,$VID2 card_label='loopback1','loopback2')
+        export VID1=${vids[0]#video}
+        export VID2=${vids[1]#video}
+        export modOptions=(video_nr=$VID1,$VID2 card_label='loopback1','loopback2')
+        echo "Using existing loopback devices: /dev/video$VID1 and /dev/video$VID2" >&2
+        echo -en "VID1=$VID1\nVID2=$VID2\n" > "$runfile"
         popd &> /dev/null
 
         return 0
     else
-        pd "v4l2loopback module is not loaded."
+        echo "v4l2loopback module is not loaded." >&2
         ${DEBUG:-false} && modinfo -n v4l2loopback
 
         # Get the next available video number for loopback devices
-        VID1=${VID1:-$( vids=( /dev/video* ) ; echo $(( ${vids[-1]#/dev/video} +1 )) )}
-        VID2=${VID2:-$(( VID1 + 1 ))}
-        modOptions=(video_nr=$VID1,$VID2 card_label='loopback1','loopback2')
+        export VID1=${VID1:-$( vids=( /dev/video* ) ; echo $(( ${vids[-1]#/dev/video} +1 )) )}
+        export VID2=${VID2:-$(( VID1 + 1 ))}
+        export modOptions=(video_nr=$VID1,$VID2 card_label='loopback1','loopback2')
         pd "Next available video numbers for loopback devices: $VID1 and $VID2"
+        [ -f "$runfile" ] && rm -f "$runfile"
 
         return 1
     fi
 }
 
+# Load the v4l2loopback module.
 modLoad () {
     modCheck && return 0
     echo "Attempting to load v4l2loopback module with sudo privileges..." >&2
     if sudo modprobe v4l2loopback "${modOptions[@]}" ; then
         pd "v4l2loopback module loaded successfully."
+        modCheck
         return 0
     else
         pd "Failed to load v4l2loopback module."
@@ -49,15 +55,16 @@ modLoad () {
     fi
 }
 
+# Remove the v4l2loopback module.
 modDelete () {
     if modCheck ; then
         echo "Attempting to remove v4l2loopback module with sudo privileges..." >&2
         if sudo modprobe -r v4l2loopback ; then
-            pd "v4l2loopback module removed successfully."
+            echo "v4l2loopback module removed successfully." >&2
             modCheck
             return 0
         else
-            pd "Failed to remove v4l2loopback module."
+            echo "Failed to remove v4l2loopback module." >&2
             return 1
         fi
     else
@@ -75,13 +82,13 @@ main () {
 
 Usage: $progn <remove>
 
-Load the v4l2loopback module to create loopback video devices for use with
-split-recordAV.sh. Run this script with the 'remove' argument to unload the
+Load the v4l2loopback module to create split video devices.
+Run this script with the 'remove' argument to unload the
 module.
 
 This script set VID1 and VID2 to the next available video numbers for loopback
 devices. If the module is already loaded, it will use the existing loopback
-devices and set VID1 and VID2 accordingly.
+devices and set VID1 and VID2 accordingly.  State information is saved to $runfile.
 
 _EOL_
         exit 1
